# Generated by Django 3.2 on 2021-05-20 05:00

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=16, verbose_name='cardNumber')),
                ('expirationDate', models.CharField(max_length=5, verbose_name='expirationDate')),
                ('cvv', models.CharField(max_length=16, verbose_name='cvv')),
                ('kzt', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='kzt')),
                ('rub', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='rub')),
                ('usd', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='usd')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', encrypted_fields.fields.EncryptedCharField(max_length=40)),
            ],
        ),
    ]
