# Generated by Django 3.2 on 2021-05-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
